name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-test-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update local toolchain
      run: |
        rustup update

    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings    

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: |
        cargo check
        cargo test --verbose
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: test-ci-cd\target\test-ci-cd.exe
        




        
